# Generated by Django 4.2.4 on 2024-08-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0003_agentvodabundleprice_superagentvodabundleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='telecel_api_active',
            field=models.BooleanField(default=False),
        ),
    ]
