# Generated by Django 4.2.4 on 2025-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0005_agentvodabundleprice_geosams_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='ishare_source',
            field=models.CharField(blank=True, choices=[('Controller', 'Controller'), ('Value4Moni', 'Value4Moni')], default='Value4Moni', max_length=250, null=True),
        ),
    ]
